### ISSUE TITLE
Dedicated Server failed to start with only this mod

### ISSUE THREAD

**Issue by trantinvan21087** [SpeakWithPlants/ghostly-elixirs-plus#1]
[server_log.txt](https://github.com/SpeakWithPlants/ghostly-elixirs-plus/files/14603892/server_log.txt)

**Comment by SpeakWithPlants** [comment]
This issue was caused by a missing reference to a function in another file.  It was hidden in the local environment by some debug options that were left enabled.  This issue is resolved.
